version: '3.3'

services:

  front:
      container_name: onson-front
      build:
        context: ./app/
        dockerfile: Dockerfile.prod
      ports:
        - "3000:3000"
      env_file:
        - ./app/.env