name: Nuxt Actions Workflow
on: push
jobs:
  build:
    runs-on: [self-hosted, prod]
    env:
      NUXT_APP_BACKEND_HOST: ${{ secrets.NUXT_APP_BACKEND_HOST }}
      VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
    container: 
      image: node:lts-alpine
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build  
